name: Deploy

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 0 * * *

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # - name: Install Doxygen and Graphviz
      #   run: sudo apt-get install -y doxygen graphviz

      - name: Install Netlify CLI
        run: |
          yarn global add netlify-cli
          echo "$(yarn global bin)" >> $GITHUB_PATH

      # - name: Generate API documentation
      #   run: python generate.py

      - name: Deploy to Netlify
        # run: netlify deploy --prod --dir Lean/_docs
        run: netlify deploy --prod --dir deprecated
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
